### PR TITLE
fix: add partner allowlist and improve wallet filtering logic

### LINKED ISSUE #12: Filter Only For Ubiquity Organizations
Image

Verify that they are associated with one of our organizations. These are technically valid "partners" but only our orgs should show on this tool so I can use it for top ups.

### PR DESCRIPTION
**Pull request by gentlementlegen**
Resolves #12 

- Introduced `getPartnerAllowlist` function for default and argument-driven allowlist generation.
- Updated `fetchAllPermits` to filter based on partner allowlist.
- Enhanced CLI to accept wallets via `--wallet`/`-w` flags.
- Updated `.env` example and README to document `GITHUB_TOKEN` usage.

### CODE REVIEW

**Comment by 0x4007** [comment]
/ask i want to get our ubiquity ubiquity-os and ubiquity-os-marketplace orgs how do i use the cli

**Comment by 0x4007** [comment]
> Caution
> 
> 401 Incorrect API key provided: sk-or-v1*************************************************************858d. You can find your API key at https://platform.openai.com/account/api-keys.

openai its not calling openrouter then.

File: src/helpers/config.ts [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+  const set = new Set<string>();
+  if (walletsFromArgs && walletsFromArgs.length > 0) {
+    walletsFromArgs
+      .map((v) => v.trim().toLowerCase())
+      .filter((v) => v.length > 0)
+      .forEach((a) => set.add(a));
+  }
+  if (set.size === 0) {
+    set.add("0x9051eDa96dB419c967189F4Ac303a290F3327680");
+    set.add("0x054Ec26398549588F3c958719bD17CC1e6E97c3C");
```
Comment (0x4007) [inline src/helpers/config.ts:16]: hard coded is a bit janky but it works for now. isnt there a better way to see the org owner or something?

Comment (gentlementlegen) [reply src/helpers/config.ts:16]: No there is no link whatsoever to the wallet owner name or org, the `location` is empty for all the partners which is why I hardcoded with a CLI option

**Review by 0x4007 — APPROVED** [review]

File: src/helpers/config.ts (hunk 1 above)
Comment (0x4007) [reply src/helpers/config.ts:16]: I guess we should write locations somehow but it isn't clear to me what event would include the location details for this.

Comment (0x4007) [reply src/helpers/config.ts:16]: Ens is made for mainnet. Officially it's network specific but in practice it could work to just respect ens. 

We had this for wallet registration. Maybe we still have it I remember implementing the logic years ago.
